FROM ubuntu

MAINTAINER kbelov "kbelov@student.42.us.org"

RUN apt-get update && apt-get upgrade -y && apt-get install -y python3.7 vim git

# To build:
# docker build -t a03 .

# To run:
# docker run --rm -ti a03
