FROM ubuntu

MAINTAINER kbelov <kbelov@student.unit.ua>

RUN apt-get update && apt-get upgrade -y && apt-get install -y default-jdk default-jre git vim emacs

# To build:
# docker build -t a04 .

# To run:
# docker run --rm -ti a04
